data:
  raw_data_path: "data/winequality-red.csv"
  test_size: 0.2
  random_state: 42

model:
  type: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    random_state: 42
    n_jobs: -1

mlflow:
  experiment_name: "wine_quality_prediction"
  tracking_uri: "mlruns"

api:
  host: "0.0.0.0"
  port: 5000
  model_path: "models/latest_model.pkl"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
